In [3]:
import numpy as np

In [4]:
my_matrix = [[1, 2, 3],[4, 5, 6], [7, 8, 9]]

In [5]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0, 101) # same as at inrange

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,5)) # rows first and columns second

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(0,10,3) # evenly spaces number between start, finish, and space between them

array([ 0.,  5., 10.])

In [21]:
np.eye(5) # identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.random.rand(2,2) # uniform distribution

array([[0.78124751, 0.47385822],
       [0.90891454, 0.14390286]])

In [23]:
np.random.randn() #standard normal distribution

In [31]:
np.random.randint(0, 101, (4,5)) # returns integers

array([[97, 37, 41,  1, 59],
       [30, 24, 52, 57, 38],
       [42, 79, 95, 64, 10],
       [ 5, 40, 96,  0, 64]])

In [33]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
# reshaping data

arr = np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr.shape

(25,)

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.shape

(25,)

In [38]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [39]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
arr_2d.shape

(3, 3)

In [41]:
arr_2d[0,2] # accessing elements on indexs

15

In [42]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [43]:
# conditional selection

In [44]:
arr = np.arange(1,11)

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [47]:
bool_arr = arr > 4

In [48]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])